#!/usr/bin/env python3
"""Generate the single-file amalgamation (M7 workstream C, docs/PACKAGING.md).

    tools/amalgamate.py -o <outdir>    ->    <outdir>/kome.h + <outdir>/kome.cpp

kome.h is the public C API (include/sync_engine.h with a provenance banner —
same include guard, so it IS sync_engine.h under the distribution name).
kome.cpp is every engine TU concatenated in dependency order: monocypher
(wrapped in extern "C"), the core headers/sources, and the transports inside
`#ifndef KOME_NO_TRANSPORT` — define KOME_NO_TRANSPORT to get the portable
core (the same subset the WASM build proves out; transports need POSIX
sockets).

The generator is pure concatenation plus include surgery: internal
(quote-form) #includes are dropped because emission order satisfies them;
nothing else is rewritten. Unity-build symbol collisions are fixed in src/
by renaming, never patched here. The full test suite runs against the
generated pair in CI (cmake -DSYNC_AMALGAMATION=ON).

The output is generated, never committed — a checked-in copy goes stale.
Releases attach it as kome-<version>-amalgamation.zip.
"""
import argparse
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

PUBLIC_HEADER = "include/sync_engine.h"
MONOCYPHER_H = "third_party/monocypher/monocypher.h"
MONOCYPHER_C = "third_party/monocypher/monocypher.c"

# Sources in the CMake SYNC_SOURCES order, split at the transport boundary.
CORE_SOURCES = [
    "src/sync_engine.cpp", "src/sha256.cpp", "src/storage.cpp",
    "src/codec.cpp", "src/reconcile.cpp", "src/crypto.cpp",
    "src/capability.cpp", "src/invite.cpp", "src/noise.cpp",
    "src/blob.cpp",
]
TRANSPORT_SOURCES = [
    "src/transport/reliable.cpp", "src/transport/udp.cpp",
    "src/transport/stun.cpp", "src/transport/cookie.cpp",
    "src/transport/relay.cpp", "src/transport/rendezvous.cpp",
    "src/transport/connection.cpp", "src/transport/tcp.cpp",
    "src/transport/ws.cpp",
]

INCLUDE_RE = re.compile(r'^\s*#\s*include\s+"([^"]+)"')


def repo_version():
    # Mirrors tools/version.sh (the shell consumers' single helper).
    m = re.search(r"^project\(sync_engine VERSION ([0-9.]+)",
                  (ROOT / "CMakeLists.txt").read_text(), re.M)
    if not m:
        sys.exit("amalgamate: could not parse project(VERSION) in CMakeLists.txt")
    return m.group(1)


def repo_commit():
    try:
        return subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                              cwd=ROOT, capture_output=True, text=True,
                              check=True).stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        return "unknown"


def banner(what, version, commit):
    return (f"/* {what}\n"
            f" *\n"
            f" * Kome {version} single-file amalgamation (commit {commit}).\n"
            f" * GENERATED by tools/amalgamate.py — do not edit; regenerate\n"
            f" * from https://github.com/HershelShah/Kome instead.\n"
            f" *\n"
            f" * License: MIT (engine) — see the LICENSE distributed with\n"
            f" * this file. Vendored monocypher: BSD-2-Clause OR CC0-1.0.\n"
            f" */\n")


def header_deps(path):
    """Quote-form includes of a header, resolved src-relative (matching -Isrc)."""
    deps = []
    for line in (ROOT / path).read_text().splitlines():
        m = INCLUDE_RE.match(line)
        if m:
            deps.append(m.group(1))
    return deps


def topo_headers(headers, satisfied=()):
    """Order headers so every quote-include points at an earlier emission.
    `headers` maps include-name (as written in #include lines, e.g.
    "transport/udp.h") -> repo path; `satisfied` names were emitted before
    this group (e.g. core headers when ordering the transports)."""
    order, done, visiting = [], set(), set()
    satisfied = set(satisfied) | {"sync_engine.h", "monocypher.h"}

    def visit(name):
        if name in done:
            return
        if name in visiting:
            sys.exit(f"amalgamate: include cycle at {name}")
        visiting.add(name)
        for dep in header_deps(headers[name]):
            if dep in headers:
                visit(dep)
            elif dep not in satisfied:
                sys.exit(f"amalgamate: {headers[name]} includes unknown \"{dep}\"")
        visiting.discard(name)
        done.add(name)
        order.append(name)

    for name in sorted(headers):
        visit(name)
    return [headers[n] for n in order]


def emit_file(out, path, known_includes):
    """Append a source file, dropping quote-form includes (emission order
    satisfies them) after validating each names something already emitted —
    pass only the includes legal for this file's section, so e.g. a core
    source including a transport header is a hard error, not a silent drop."""
    out.append(f"/* ---------- begin: {path} ---------- */")
    for line in (ROOT / path).read_text().splitlines():
        m = INCLUDE_RE.match(line)
        if m:
            if m.group(1) not in known_includes:
                sys.exit(f"amalgamate: {path} includes unknown \"{m.group(1)}\"")
            continue
        out.append(line)
    out.append(f"/* ---------- end: {path} ---------- */")
    out.append("")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("-o", "--outdir", type=Path)
    ap.add_argument("--print-version", action="store_true",
                    help="print the engine version (from CMake project()) and exit")
    args = ap.parse_args()
    if args.print_version:
        print(repo_version())
        return
    if not args.outdir:
        ap.error("-o/--outdir is required")
    args.outdir.mkdir(parents=True, exist_ok=True)

    version, commit = repo_version(), repo_commit()

    # The TU lists above are the CMake SYNC_SOURCES split at the transport
    # boundary; fail loudly if a source was added to one side only.
    on_disk = {str(p.relative_to(ROOT))
               for p in (ROOT / "src").rglob("*.cpp")}
    listed = set(CORE_SOURCES) | set(TRANSPORT_SOURCES)
    if on_disk != listed:
        sys.exit("amalgamate: source lists drifted from src/**/*.cpp — "
                 f"missing here: {sorted(on_disk - listed)}, "
                 f"stale here: {sorted(listed - on_disk)}")

    core_headers = {p.name: f"src/{p.name}"
                    for p in (ROOT / "src").iterdir()
                    if p.suffix in (".h", ".hpp")}
    transport_headers = {f"transport/{p.name}": f"src/transport/{p.name}"
                         for p in (ROOT / "src/transport").iterdir()
                         if p.suffix == ".h"}

    # Section-scoped include whitelists: the core (headers and sources) may
    # never include a transport header — topo_headers enforces it for the
    # headers, the narrower `known_core` enforces it for the sources.
    known_core = set(core_headers) | {"sync_engine.h", "monocypher.h"}
    known = known_core | set(transport_headers)

    # kome.h — the public C API under the distribution name.
    public = (ROOT / PUBLIC_HEADER).read_text()
    (args.outdir / "kome.h").write_text(
        banner("kome.h — public C API (include/sync_engine.h).", version, commit)
        + public)

    # kome.cpp — everything else, single TU.
    out = [banner("kome.cpp — the entire engine as one translation unit.\n"
                  " *\n"
                  " * Build:  c++ -std=c++17 -O2 -c kome.cpp\n"
                  " * Then link kome.o into your C or C++ program and use the\n"
                  " * pure-C API in kome.h. Define KOME_NO_TRANSPORT for the\n"
                  " * portable core (no POSIX sockets).", version, commit),
           "#define KOME_AMALGAMATION 1", ""]

    emit_file(out, PUBLIC_HEADER, known_core)     # own guard == kome.h's
    emit_file(out, MONOCYPHER_H, known_core)      # has extern "C" guards
    out.append('extern "C" {')
    emit_file(out, MONOCYPHER_C, known_core)
    out.append('} /* extern "C" (monocypher) */')
    out.append("")

    for path in topo_headers(core_headers):
        emit_file(out, path, known_core)
    for path in CORE_SOURCES:
        emit_file(out, path, known_core)

    out.append("#ifndef KOME_NO_TRANSPORT")
    out.append("")
    for path in topo_headers(transport_headers, satisfied=set(core_headers)):
        emit_file(out, path, known)
    for path in TRANSPORT_SOURCES:
        emit_file(out, path, known)
    out.append("#endif /* KOME_NO_TRANSPORT */")

    (args.outdir / "kome.cpp").write_text("\n".join(out) + "\n")
    print(f"amalgamate: wrote {args.outdir}/kome.h + kome.cpp "
          f"(Kome {version}, commit {commit})")


if __name__ == "__main__":
    main()
