#!/usr/bin/env python3
"""Turn an lcov .info file into docs/COVERAGE.md (per-file table + totals)."""
import sys, subprocess, datetime, os

def parse(info):
    files = {}
    sf = None
    for line in open(info):
        line = line.strip()
        if line.startswith("SF:"):
            sf = line[3:]
            files[sf] = dict(LF=0, LH=0, FNF=0, FNH=0, BRF=0, BRH=0)
        elif line.startswith("LF:"): files[sf]["LF"] = int(line[3:])
        elif line.startswith("LH:"): files[sf]["LH"] = int(line[3:])
        elif line.startswith("FNF:"): files[sf]["FNF"] = int(line[4:])
        elif line.startswith("FNH:"): files[sf]["FNH"] = int(line[4:])
        elif line.startswith("BRF:"): files[sf]["BRF"] = int(line[4:])
        elif line.startswith("BRH:"): files[sf]["BRH"] = int(line[4:])
    return files

def pct(h, f): return 100.0 * h / f if f else 100.0

def main():
    info = sys.argv[1]
    files = parse(info)
    root = os.path.basename(os.getcwd())
    rows = []
    tLF = tLH = tFNF = tFNH = 0
    for sf, d in files.items():
        name = sf
        for marker in ("/src/", "/include/", "/services/"):
            if marker in name:
                name = name[name.index(marker) + 1:]
                break
        else:
            name = os.path.basename(name)
        rows.append((name, d))
        tLF += d["LF"]; tLH += d["LH"]; tFNF += d["FNF"]; tFNH += d["FNH"]
    rows.sort(key=lambda r: pct(r[1]["LH"], r[1]["LF"]))

    try:
        commit = subprocess.check_output(["git", "rev-parse", "--short", "HEAD"]).decode().strip()
    except Exception:
        commit = "?"
    date = datetime.date.today().isoformat()

    out = []
    out.append("# Test coverage\n")
    out.append(f"Generated by `tools/coverage.sh` (lcov) at commit `{commit}` on {date}. "
               "Engine code only — third_party, tests, and GoogleTest are excluded.\n")
    out.append(f"**Overall: {pct(tLH,tLF):.1f}% lines ({tLH}/{tLF}), "
               f"{pct(tFNH,tFNF):.1f}% functions ({tFNH}/{tFNF}).**\n")
    out.append("| File | Lines | Line % | Func % |")
    out.append("|------|-------|--------|--------|")
    for name, d in rows:
        out.append(f"| `{name}` | {d['LH']}/{d['LF']} | "
                   f"{pct(d['LH'],d['LF']):.1f}% | {pct(d['FNH'],d['FNF']):.1f}% |")
    out.append("")
    out.append("Sorted worst-first. Lines that are unreachable defensive paths "
               "(OOM, internal-error catch-alls) and the demo/daemon mains are "
               "expected to be partially covered.")
    print("\n".join(out))

if __name__ == "__main__":
    main()
